[package]
name = "stwo_cairo_verifier"
version = "0.1.0"
edition = "2024_07"

[lib]
casm = true

[cairo]
inlining-strategy = "avoid"

[tool.fmt]
sort-module-level-items = true

[dependencies]

[dev-dependencies]
cairo_test = "2.8.0"
# snforge_std = { path = "/Users/andrewmilson/projects/playground/starknet-foundry/snforge_std" }
# # # TODO(andrew): Remove once get scarb >=2.8.3 working.
# assert_macros = "2.8.4"


# [scripts]
# test = "snforge test --max-n-steps 100000000"
